# Generated by Django 4.2.29 on 2026-03-24 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import utils.cep.check_cep
import utils.city.check_city
import utils.cpf.check_cpf
import utils.phone.check_phone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0005_person_companion_name_person_companion_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPerson',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da mãe')),
                ('born_date', models.DateField(blank=True, help_text='Exemplo: 03/12/2015', null=True, verbose_name='Dt. nascimento')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='Dt. óbito')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=100, null=True, verbose_name='E-mail')),
                ('companion_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do acompanhante')),
                ('companion_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone do acompanhante')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, null=True, verbose_name='Gênero')),
                ('cpf', models.CharField(blank=True, db_index=True, help_text='Exemplo: 00000000000', max_length=14, null=True, validators=[utils.cpf.check_cpf.check_cpf], verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=14, null=True, verbose_name='RG')),
                ('rg_ssp', models.CharField(blank=True, choices=[('SP', 'São Paulo'), ('PR', 'Paraná'), ('SC', 'Santa Catarina'), ('RS', 'Rio Grande do Sul'), ('MS', 'Mato Grosso do Sul'), ('RO', 'Rondônia'), ('AC', 'Acre'), ('AM', 'Amazonas'), ('RR', 'Roraima'), ('PA', 'Pará'), ('AP', 'Amapá'), ('TO', 'Tocantins'), ('MA', 'Maranhão'), ('RN', 'Rio Grande do Norte'), ('PB', 'Paraíba'), ('PE', 'Pernambuco'), ('AL', 'Alagoas'), ('SE', 'Sergipe'), ('BA', 'Bahia'), ('MG', 'Minas Gerais'), ('RJ', 'Rio de Janeiro'), ('MT', 'Mato Grosso'), ('GO', 'Goiás'), ('DF', 'Distrito Federal'), ('PI', 'Piauí'), ('CE', 'Ceará'), ('ES', 'Espírito Santo')], max_length=2, null=True, verbose_name='SSP')),
                ('state', models.CharField(blank=True, choices=[('SP', 'São Paulo'), ('PR', 'Paraná'), ('SC', 'Santa Catarina'), ('RS', 'Rio Grande do Sul'), ('MS', 'Mato Grosso do Sul'), ('RO', 'Rondônia'), ('AC', 'Acre'), ('AM', 'Amazonas'), ('RR', 'Roraima'), ('PA', 'Pará'), ('AP', 'Amapá'), ('TO', 'Tocantins'), ('MA', 'Maranhão'), ('RN', 'Rio Grande do Norte'), ('PB', 'Paraíba'), ('PE', 'Pernambuco'), ('AL', 'Alagoas'), ('SE', 'Sergipe'), ('BA', 'Bahia'), ('MG', 'Minas Gerais'), ('RJ', 'Rio de Janeiro'), ('MT', 'Mato Grosso'), ('GO', 'Goiás'), ('DF', 'Distrito Federal'), ('PI', 'Piauí'), ('CE', 'Ceará'), ('ES', 'Espírito Santo')], max_length=2, null=True, verbose_name='Estado')),
                ('address_line_1', models.CharField(blank=True, help_text='Rua e número da residência', max_length=100, null=True, verbose_name='Endereço (linha 1)')),
                ('address_line_2', models.CharField(blank=True, help_text='Complemento (apartamento, bloco,...)', max_length=100, null=True, verbose_name='Endereço (linha 2)')),
                ('neighbourhood', models.CharField(blank=True, max_length=60, null=True, verbose_name='Bairro')),
                ('city', models.CharField(blank=True, max_length=60, null=True, validators=[utils.city.check_city.check_city], verbose_name='Cidade')),
                ('postal_code', models.CharField(blank=True, help_text='Exemplo: 00000000', max_length=15, null=True, validators=[utils.cep.check_cep.check_cep], verbose_name='CEP')),
                ('residence_type', models.CharField(blank=True, choices=[('urban', 'Urbano'), ('rural', 'Rural')], max_length=6, null=True, verbose_name='Distrito')),
                ('ddd_private_phone', models.CharField(blank=True, choices=[('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48'), ('49', '49'), ('50', '50'), ('51', '51'), ('52', '52'), ('53', '53'), ('54', '54'), ('55', '55'), ('56', '56'), ('57', '57'), ('58', '58'), ('59', '59'), ('60', '60'), ('61', '61'), ('62', '62'), ('63', '63'), ('64', '64'), ('65', '65'), ('66', '66'), ('67', '67'), ('68', '68'), ('69', '69'), ('70', '70'), ('71', '71'), ('72', '72'), ('73', '73'), ('74', '74'), ('75', '75'), ('76', '76'), ('77', '77'), ('78', '78'), ('79', '79'), ('80', '80'), ('81', '81'), ('82', '82'), ('83', '83'), ('84', '84'), ('85', '85'), ('86', '86'), ('87', '87'), ('88', '88'), ('89', '89'), ('90', '90'), ('91', '91'), ('92', '92'), ('93', '93'), ('94', '94'), ('95', '95'), ('96', '96'), ('97', '97'), ('98', '98'), ('99', '99')], help_text='Apenas 2 dígitos', max_length=2, null=True, verbose_name='DDD')),
                ('private_phone', models.CharField(blank=True, help_text='Exemplo: 999999999', max_length=10, null=True, validators=[utils.phone.check_phone.check_phone], verbose_name='Tel. p/ contato')),
                ('ddd_message_phone', models.CharField(blank=True, choices=[('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48'), ('49', '49'), ('50', '50'), ('51', '51'), ('52', '52'), ('53', '53'), ('54', '54'), ('55', '55'), ('56', '56'), ('57', '57'), ('58', '58'), ('59', '59'), ('60', '60'), ('61', '61'), ('62', '62'), ('63', '63'), ('64', '64'), ('65', '65'), ('66', '66'), ('67', '67'), ('68', '68'), ('69', '69'), ('70', '70'), ('71', '71'), ('72', '72'), ('73', '73'), ('74', '74'), ('75', '75'), ('76', '76'), ('77', '77'), ('78', '78'), ('79', '79'), ('80', '80'), ('81', '81'), ('82', '82'), ('83', '83'), ('84', '84'), ('85', '85'), ('86', '86'), ('87', '87'), ('88', '88'), ('89', '89'), ('90', '90'), ('91', '91'), ('92', '92'), ('93', '93'), ('94', '94'), ('95', '95'), ('96', '96'), ('97', '97'), ('98', '98'), ('99', '99')], help_text='Apenas 2 dígitos', max_length=2, null=True, verbose_name='DDD')),
                ('message_phone', models.CharField(blank=True, help_text='Exemplo: 999999999', max_length=10, null=True, validators=[utils.phone.check_phone.check_phone], verbose_name='Tel. p/ mensagem')),
                ('observation', models.TextField(blank=True, max_length=600, null=True, verbose_name='Observação')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Pessoa',
                'verbose_name_plural': 'historical Pessoas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
