# Generated by Django 4.2.29 on 2026-03-24 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_historicalperson'),
    ]

    operations = [
    ]
